inherit_from: configs/unconditional/onet_airplanes_pretrained.yaml
data:
  dataset: images
  path: demo
training:
  out_dir:  demo
generation:
  generation_dir: generation
  refinement_step: 100
  simplify_nfaces: 2500
